version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: db_co2runter
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD
  TOKEN_KEY: adjuhskajdkjas

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_HOST: localhost

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "9001:80"

  api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile-Prod
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
      NODE_ENV: production

  client:
    stdin_open: true
    environment:
      - WDS_SOCKET_PORT=3050
    build:
      dockerfile: Dockerfile-Prod
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

        